A Faker test data generation tool with a simplistic performance test.
finopsfoundation/focus_validator pull request #108
Opened 2023-12-19 01:07 UTC by johrenberger

While experimenting with Python and Faker I found that the test data samples could benefit from a more dynamic, scalable tool to more efficiently generate data on the fly.

csv_random_data_generator.py - This class has the Faker structure in place with several of the variables customized with AWS specific data. This lended to more realistic data generated at random. The bottom of the file includes several commands to generate an inital file (also attached) with 1000 records. There are opportunities to enhance it to include google or Azure options as well.

focus_validator_performance_test.py - Super simple performance test that exercises the 1,000 record csv to see what it's performance capabilities are. This can be enhanced for more complex scaling, created more for curiousity.

I am not a Python expert but thought the data generation would be useful for generating more interesting, on the fly, scaled data samples for testing.

2023-12-19 01:20 UTC, johrenberger reviewed
Signed-off-by: Justin Ohrenberger <justinohrenberger@gmail.com>

2024-01-04 22:33 UTC, varunmittal91 requested changes

2024-01-05 01:34 UTC, johrenberger commented on .github/workflows/publish.yaml
> +cdname: Publish
Looks like there was a mistake there. Thanks for catching.

2024-01-05 01:38 UTC, johrenberger commented on tests/samples/csv_random_data_generator.py
> +       self.AmortizedCost = fake.pyfloat(left_digits=3,right_digits=2, positive=True)
This was pulled from https://github.com/finopsfoundation/focus_validator/blob/main/tests/samples/all_pass.csv

This aligns with: https://github.com/finopsfoundation/focus_validator/blob/main/focus_validator/rules/base_rule_definitions/FV-M002-0003.yaml

Happy to change the name in my code but there may be another inconsistency to correct.

2024-01-05 02:02 UTC, johrenberger commented on .gitignore
Agreed, file rolled back to original version.

2024-01-05 11:32 UTC, merged